---
title: "Strategy to Launch"
---

```{r global_options, include=FALSE}
library(knitr)
library(tidyverse)
library(colorspace)
library(cowplot)
library(dplyr)
library(scales)

opts_chunk$set(fig.align="center", fig.height=4, fig.width=5.5)
```

Load the data from STL reporting and DPG reporting and compare
```{r message = FALSE}
# load data
STL_spend <- read_csv("data\\STL_funding_levels_no_formatting.csv"
  # , col_types = cols("Roadmap amounts (000's)" = col_double())
  )
STL_spend
unique(STL_spend$"Roadmap_amounts")

colnames(STL_spend)
```

```{r message = FALSE}
colnames(STL_spend)

# scaleFactor <- max(STL_spend$Roadmap_projects) / max(STL_spend$Roadmap_amounts)

# plot number of projects and cost by FY
ggplot(STL_spend, aes(x = FY, y = Roadmap_projects, label = Roadmap_amounts)) +
  # set up project visual
    # change scale of data values to align with fund funding scale
    # add vertical bars for funding levels
  geom_col(aes(y = Roadmap_amounts), fill = "steelblue", alpha = 0.8) + 
  geom_line(aes(
    y = Roadmap_projects * 500, group = 1, 
    linetype = "# of projects"), 
    color = "blue", linewidth = 1.7, alpha = 0.7
    ) +
  # add points for project numbers, possibly labels - depends on clutter
    # change scale of points to align with fund funding scale
  geom_point(aes(y = Roadmap_projects * 500), size = 2, color = "blue") +
  scale_y_continuous(
    name = "$ (000's)", 
    # re-scale secondary axis to accommodate previous scalings
    sec.axis=sec_axis(~./500, name="# projects")
    ) +
  theme_bw() + 
  ggtitle("STL Roadmap Funded") + 
  geom_text(
    # use labeler package to represent amounts in millions
    aes(label = label_number_si()(Roadmap_amounts*1000)), 
    vjust = -0.5, 
    color = "white"
    ) +
  theme(
    # simplify background elements
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(), 
    panel.border = element_blank(), 
    plot.title = element_text((hjust = 10)),
    # axis.title.x = element_text(margin = margin(t = 5)),
    # nudge axis text positions
    axis.text.x.bottom = element_text(margin = margin(t = 5)),
    axis.title.y.right = element_text(vjust = 2),
    axis.title.y.left = element_text(vjust = 2),
    legend.position = c(0.95,0.95),
    legend.title = element_blank(),
    ) +
  xlab("Fiscal Year")

# next do for self-funded

```


```{r message = FALSE}
# self-fund
colnames(STL_spend)

# plot number of projects and cost by FY
ggplot(STL_spend, aes(x = FY, y = Roadmap_projects, label = Roadmap_amounts)) +
  # set up project visual
    # change scale of data values to align with fund funding scale
  geom_col(aes(y = Self_amounts), fill = "steelblue", alpha = 0.8) + 
  geom_line(aes(
    y = Self_projects * 100, group = 1, 
    linetype = "# of projects"), 
    color = "blue", linewidth = 1.7, alpha = 0.7
    ) +
  # add points for project numbers, possibly labels - depends on clutter
    # change scale of points to align with fund funding scale
  geom_point(aes(y = Self_projects * 100), size = 2, color = "blue") +
  # add vertical bars for funding levels

  scale_y_continuous(
    name = "$ (000's)", 
    # re-scale secondary axis to accommodate previous scalings
    sec.axis=sec_axis(~./100, name="# projects")
    ) +
  theme_bw() + 
  ggtitle("STL Self-Funded") + 
  geom_text(
    # use labeler package to represent amounts in millions
    aes(label = label_number_si()(Self_amounts*1000)), 
    vjust = -0.5, 
    color = "white"
    ) +
  theme(
    # simplify background elements
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(), 
    panel.border = element_blank(), 
    plot.title = element_text((hjust = 10)),
    # axis.title.x = element_text(margin = margin(t = 5)),
    # nudge axis text positions
    axis.text.x.bottom = element_text(margin = margin(t = 5)),
    axis.title.y.right = element_text(vjust = 2),
    axis.title.y.left = element_text(vjust = 2),
    legend.position = c(0.95,0.95),
    legend.title = element_blank(),
    ) +
  xlab("Fiscal Year")
  # ylim(0, 2000)

```


```{r message = FALSE}
#facet wrap by year and groupby project spend of roadmap & self in side-by-side
# bars, wrapped with vars = FY

unique(STL_spend$"Roadmap amounts (000's)")

ggplot(STL_spend, aes_strin(FY, "Total (000's)")) +
  geom_point() +
  geom_line() +
  geom_text(aes(label = "Total (000's)", vjust = -0.5))

colnames(STL_spend)
STL_spend
colnames(mtcars)
ggplot(mtcars, aes(y = cyl)) + geom_bar()
```


```{r message = FALSE}
# ylim(0, 200000)

ggplot(STL_spend, aes(x = FY, y = "Total (000's)", group = "Total (000's)")) +
  geom_point() +
  geom_line()
```


```{r message = FALSE}
```
---
It looks like the differences in the datasets are not too disparate; attributing
most of this too snapshot in time, whether before or after a key decision; 
trends are the same.  Will use DPG data to have less friction in future discussions.
---